name: simplevoting
recipe: drupal11
services:
  appserver:
    type: php:8.3
    via: apache
    webroot: web
    xdebug: true
  config:
    php: .vscode/php.ini

  database:
    type: mariadb:10.11
    portforward: true
    creds:
      database: simplevoting
      user: simplevoting
      password: simplevoting

proxy:
  appserver:
    - simplevoting.lndo.site

tooling:
  composer:
    service: appserver
  php:
    service: appserver
  drush:
    service: appserver
    cmd: /app/vendor/bin/drush
